#!/bin/bash
UDEV_RULES_FOLDER="/etc/udev/rules.d"
mkdir -p "$UDEV_RULES_FOLDER"
DEST="$UDEV_RULES_FOLDER/99-joystick_events.rules"
URL="https://raw.githubusercontent.com/EnriqueWood/batocera-patches/main/extras$DEST"

mkdir -p "$(dirname "$DEST")"
wget -q -O "$DEST" "$URL"
batocera-save-overlay
udevadm control --reload-rules
udevadm trigger
