#!/bin/bash
## This script enables wake from suspension capabilities to every bluetooth device (useful for bluetooth controllers)
mkdir -p "/userdata/system/logs/"
SERVICES_FOLDER="/userdata/system/services"
SERVICE_NAME="wake_on_bluetooth"
DEST="$SERVICES_FOLDER/$SERVICE_NAME"
URL="https://raw.githubusercontent.com/EnriqueWood/batocera-patches/main/extras$DEST"
mkdir -p "$(dirname "$DEST")"

wget -q -O "$DEST" "$URL"
chmod +x "$DEST"

batocera-services enable "$SERVICE_NAME"
batocera-services start "$SERVICE_NAME"
