#!/bin/bash
## Execute all user-defined scripts located in the EmulationStation sleep and wake directories upon system suspend and resume events

SCRIPTS_BASE_PATH=/userdata/system/configs/emulationstation/scripts
case "$1" in
    suspend)
        if [[ -d $SCRIPTS_BASE_PATH/suspend ]]; then
            for script in $SCRIPTS_BASE_PATH/suspend/*; do
                [[ -x $script ]] && /bin/bash $script
            done
        fi
    ;;
    resume|thaw)
        if [[ -d $SCRIPTS_BASE_PATH/resume ]]; then
            for script in $SCRIPTS_BASE_PATH/resume/*; do
                [[ -x $script ]] && /bin/bash $script
            done
        fi
    ;;
esac
